/** `GET https://api.tcgdex.net/v2/en/types`, captured 2026-09-21. */
export const CARD_TYPES = [
  'Colorless',
  'Darkness',
  'Dragon',
  'Fairy',
  'Fighting',
  'Fire',
  'Grass',
  'Lightning',
  'Metal',
  'Psychic',
  'Water',
] as const;

/** `GET https://api.tcgdex.net/v2/en/rarities`, captured 2026-09-21. */
export const CARD_RARITIES = [
  'ACE SPEC Rare',
  'Amazing Rare',
  'Black White Rare',
  'Classic Collection',
  'Common',
  'Crown',
  'Double rare',
  'Four Diamond',
  'Full Art Trainer',
  'Futuristic Rare',
  'Holo Rare',
  'Holo Rare V',
  'Holo Rare VMAX',
  'Holo Rare VSTAR',
  'Hyper rare',
  'Illustration rare',
  'LEGEND',
  'Mega Hyper Rare',
  'None',
  'One Diamond',
  'One Shiny',
  'One Star',
  'Pikachu Rare',
  'Promo',
  'Radiant Rare',
  'Rare',
  'Rare Holo',
  'Rare Holo LV.X',
  'Rare PRIME',
  'Secret Rare',
  'Shiny Ultra Rare',
  'Shiny rare',
  'Shiny rare V',
  'Shiny rare VMAX',
  'Special illustration rare',
  'Three Diamond',
  'Three Star',
  'Two Diamond',
  'Two Shiny',
  'Two Star',
  'Ultra Rare',
  'Uncommon',
] as const;

/** Card aspect ratio, for placeholders that must not reflow the grid. */
export const CARD_ASPECT = '63 / 88';
