import type { Card } from '../lib/tcgdex';

/**
 * The example cards `effect-gallery.ts` shows, as TCGdex actually serves them —
 * so `effect-gallery.test.ts` can run the real `selectHolo` on the real card
 * without touching the network.
 *
 * Captured from `GET https://api.tcgdex.net/v2/en/cards/{id}` on 2026-09-23
 * and trimmed to what `selectHolo` reads (`rarity`, `suffix`, `localId`,
 * `category`, `stage`), the reverse-printing flag (`variants`) and what the
 * `Card` type requires. Every value is copied verbatim: never edit one by hand
 * to make a test pass — re-fetch the card instead. Re-capture them all if
 * `selectHolo` ever starts reading a field that is not here.
 */
export const CAPTURED_CARDS: Readonly<Record<string, Card>> = {
  'sm7.5-1': {
    id: 'sm7.5-1',
    localId: '1',
    name: 'Charmander',
    category: 'Pokemon',
    set: { id: 'sm7.5', name: 'Dragon Majesty', cardCount: { total: 78, official: 70 } },
    rarity: 'Common',
    stage: 'Basic',
    variants: { firstEdition: false, holo: false, normal: true, reverse: false, wPromo: false },
  },
  'swsh3-25': {
    id: 'swsh3-25',
    localId: '25',
    name: 'Heatran',
    category: 'Pokemon',
    set: { id: 'swsh3', name: 'Darkness Ablaze', cardCount: { total: 201, official: 189 } },
    rarity: 'Holo Rare',
    stage: 'Basic',
    variants: { firstEdition: false, holo: true, normal: false, reverse: true, wPromo: false },
  },
  'cel25cc-CC001': {
    id: 'cel25cc-CC001',
    localId: 'CC001',
    name: 'Blastoise',
    category: 'Pokemon',
    set: {
      id: 'cel25cc',
      name: 'Celebrations Classic Collection',
      cardCount: { total: 25, official: 25 },
    },
    rarity: 'Classic Collection',
    stage: 'Stage2',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
  },
  'swsh4-9': {
    id: 'swsh4-9',
    localId: '9',
    name: 'Celebi',
    category: 'Pokemon',
    set: { id: 'swsh4', name: 'Vivid Voltage', cardCount: { total: 203, official: 185 } },
    rarity: 'Amazing Rare',
    stage: 'Basic',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
  },
  'swsh10.5-004': {
    id: 'swsh10.5-004',
    localId: '004',
    name: 'Radiant Venusaur',
    category: 'Pokemon',
    set: { id: 'swsh10.5', name: 'Pokémon GO', cardCount: { total: 88, official: 78 } },
    rarity: 'Radiant Rare',
    stage: 'Basic',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
  },
  'sv06.5-095': {
    id: 'sv06.5-095',
    localId: '095',
    name: 'Pecharunt ex',
    category: 'Pokemon',
    set: { id: 'sv06.5', name: 'Shrouded Fable', cardCount: { total: 99, official: 64 } },
    rarity: 'Hyper rare',
    stage: 'Basic',
    suffix: 'ex',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
  },
  'A1a-085': {
    id: 'A1a-085',
    localId: '085',
    name: 'Celebi ex',
    category: 'Pokemon',
    set: { id: 'A1a', name: 'Mythical Island', cardCount: { total: 86, official: 68 } },
    rarity: 'Three Star',
    stage: 'Basic',
    suffix: 'EX',
    variants: { firstEdition: false, holo: false, normal: true, reverse: false, wPromo: false },
  },
  'sv06.5-090': {
    id: 'sv06.5-090',
    localId: '090',
    name: 'Okidogi ex',
    category: 'Pokemon',
    set: { id: 'sv06.5', name: 'Shrouded Fable', cardCount: { total: 99, official: 64 } },
    rarity: 'Special illustration rare',
    stage: 'Basic',
    suffix: 'ex',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
  },
  'sv04.5-092': {
    id: 'sv04.5-092',
    localId: '092',
    name: 'Oddish',
    category: 'Pokemon',
    set: { id: 'sv04.5', name: 'Paldean Fates', cardCount: { total: 245, official: 91 } },
    rarity: 'Shiny rare',
    stage: 'Basic',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
  },
  'swsh4.5sv-SV105': {
    id: 'swsh4.5sv-SV105',
    localId: 'SV105',
    name: 'Rillaboom V',
    category: 'Pokemon',
    set: {
      id: 'swsh4.5sv',
      name: 'Shining Fates Shiny Vault',
      cardCount: { total: 122, official: 122 },
    },
    rarity: 'Shiny rare V',
    stage: 'Basic',
    suffix: 'V',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
  },
  'swsh4.5sv-SV106': {
    id: 'swsh4.5sv-SV106',
    localId: 'SV106',
    name: 'Rillaboom VMAX',
    category: 'Pokemon',
    set: {
      id: 'swsh4.5sv',
      name: 'Shining Fates Shiny Vault',
      cardCount: { total: 122, official: 122 },
    },
    rarity: 'Shiny rare VMAX',
    stage: 'VMAX',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
  },
  'sv03.5-003': {
    id: 'sv03.5-003',
    localId: '003',
    name: 'Venusaur ex',
    category: 'Pokemon',
    set: { id: 'sv03.5', name: '151', cardCount: { total: 207, official: 165 } },
    rarity: 'Double rare',
    stage: 'Stage2',
    suffix: 'ex',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
  },
  'sv03.5-182': {
    id: 'sv03.5-182',
    localId: '182',
    name: 'Venusaur ex',
    category: 'Pokemon',
    set: { id: 'sv03.5', name: '151', cardCount: { total: 207, official: 165 } },
    rarity: 'Ultra Rare',
    stage: 'Stage2',
    suffix: 'ex',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
  },
  'swsh3-2': {
    id: 'swsh3-2',
    localId: '2',
    name: 'Butterfree VMAX',
    category: 'Pokemon',
    set: { id: 'swsh3', name: 'Darkness Ablaze', cardCount: { total: 201, official: 189 } },
    rarity: 'Holo Rare VMAX',
    stage: 'VMAX',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
  },
  'swsh12-008': {
    id: 'swsh12-008',
    localId: '008',
    name: 'Serperior VSTAR',
    category: 'Pokemon',
    set: { id: 'swsh12', name: 'Silver Tempest', cardCount: { total: 215, official: 195 } },
    rarity: 'Holo Rare VSTAR',
    stage: 'VSTAR',
    suffix: 'V',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
  },
  'sv03.5-166': {
    id: 'sv03.5-166',
    localId: '166',
    name: 'Bulbasaur',
    category: 'Pokemon',
    set: { id: 'sv03.5', name: '151', cardCount: { total: 207, official: 165 } },
    rarity: 'Illustration rare',
    stage: 'Basic',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
  },
  '30th-023': {
    id: '30th-023',
    localId: '023',
    name: 'Pikachu',
    category: 'Pokemon',
    set: { id: '30th', name: '30th Celebration', cardCount: { total: 158, official: 128 } },
    rarity: 'Pikachu Rare',
    stage: 'Basic',
    variants: { firstEdition: false, holo: false, normal: true, reverse: false, wPromo: false },
  },
  'swsh3-3': {
    id: 'swsh3-3',
    localId: '3',
    name: 'Paras',
    category: 'Pokemon',
    set: { id: 'swsh3', name: 'Darkness Ablaze', cardCount: { total: 201, official: 189 } },
    rarity: 'Common',
    stage: 'Basic',
    variants: { firstEdition: false, holo: false, normal: true, reverse: true, wPromo: false },
  },
  'swsh12tg-TG12': {
    id: 'swsh12tg-TG12',
    localId: 'TG12',
    name: 'Kricketune V',
    category: 'Pokemon',
    set: {
      id: 'swsh12tg',
      name: 'Silver Tempest Trainer Gallery',
      cardCount: { total: 30, official: 30 },
    },
    rarity: 'Holo Rare V',
    stage: 'Basic',
    suffix: 'V',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
  },
  'swsh12tg-TG15': {
    id: 'swsh12tg-TG15',
    localId: 'TG15',
    name: 'Blaziken VMAX',
    category: 'Pokemon',
    set: {
      id: 'swsh12tg',
      name: 'Silver Tempest Trainer Gallery',
      cardCount: { total: 30, official: 30 },
    },
    rarity: 'Holo Rare VMAX',
    stage: 'VMAX',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
  },
  'swsh12tg-TG29': {
    id: 'swsh12tg-TG29',
    localId: 'TG29',
    name: 'Rayquaza VMAX',
    category: 'Pokemon',
    set: {
      id: 'swsh12tg',
      name: 'Silver Tempest Trainer Gallery',
      cardCount: { total: 30, official: 30 },
    },
    rarity: 'Secret Rare',
    stage: 'VMAX',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
  },
  'swsh12tg-TG23': {
    id: 'swsh12tg-TG23',
    localId: 'TG23',
    name: 'Friends in Galar',
    category: 'Trainer',
    set: {
      id: 'swsh12tg',
      name: 'Silver Tempest Trainer Gallery',
      cardCount: { total: 30, official: 30 },
    },
    rarity: 'Full Art Trainer',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
  },
};
