import type { Card } from '../lib/tcgdex';

/**
 * The example cards `effect-gallery.ts` shows, three per effect, as TCGdex
 * actually serves them — so `effect-gallery.test.ts` can run the real
 * `selectHolo` on the real card without touching the network.
 *
 * Captured from `GET https://api.tcgdex.net/v2/en/cards/{id}` and trimmed to
 * what `selectHolo` reads (`rarity`, `suffix`, `localId`, `category`,
 * `trainerType`, `stage`, the set id it takes off `id` for the card's era, and each
 * printing's `type` and `foil` in `variants_detailed`, for a Poké Ball
 * reverse), the reverse-printing flag (`variants`), the `image` the page
 * draws, and what the `Card` type requires. The first 87 were fetched on
 * 2026-09-24, when the page grew to 29 sections: the 33 new to it were
 * captured then, and the 54 it kept from the 66-card page (captured
 * 2026-09-23 and 2026-09-24) matched that fetch in every field. Three more,
 * dp7-96, hgss3-83 and me01-034, came on 2026-09-25 with the page's 30th
 * section, sv-rare-holo, whose two other cards moved over from regular-holo.
 * All 90 were fetched again later that day, when selection began reading
 * `variants_detailed`: every field already here matched, and Prismatic
 * Evolutions' Eevee (sv08.5-074) replaced 151's Wartortle; with the Master
 * Ball printing, its Exeggcute (sv08.5-001, captured the same day) replaced
 * 151's Squirtle. All 90 were fetched once more that day, when selection
 * began reading `trainerType`: every field matched, the nine trainers took
 * theirs, and the Trainer Gallery's Abomasnow (swsh10tg-TG01) and Charizard
 * (swsh11tg-TG03) replaced its Piers and Opal, full art trainers now. The subset-set cards
 * (`swsh4.5sv-…` and the `swsh9tg`–`swsh12tg` Trainer Gallery ones) have no
 * `image` because the API links none: `lib/images.ts#cardImageBase` finds
 * their art. Every value is copied verbatim: never edit one by hand to make a
 * test pass — re-fetch the card instead. Re-capture them all if `selectHolo`,
 * or the page, ever starts reading a field that is not here.
 */
export const CAPTURED_CARDS: Readonly<Record<string, Card>> = {
  'sm1-1': {
    id: 'sm1-1',
    localId: '1',
    name: 'Caterpie',
    image: 'https://assets.tcgdex.net/en/sm/sm1/1',
    category: 'Pokemon',
    set: { id: 'sm1', name: 'Sun & Moon', cardCount: { total: 172, official: 149 } },
    rarity: 'Common',
    stage: 'Basic',
    variants: { firstEdition: false, holo: false, normal: true, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'normal' }],
  },
  'det1-1': {
    id: 'det1-1',
    localId: '1',
    name: 'Bulbasaur',
    image: 'https://assets.tcgdex.net/en/sm/det1/1',
    category: 'Pokemon',
    set: { id: 'det1', name: 'Detective Pikachu', cardCount: { total: 18, official: 18 } },
    rarity: 'Common',
    stage: 'Basic',
    variants: { firstEdition: false, holo: false, normal: true, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'normal' }],
  },
  'sm7-1': {
    id: 'sm7-1',
    localId: '1',
    name: 'Bellsprout',
    image: 'https://assets.tcgdex.net/en/sm/sm7/1',
    category: 'Pokemon',
    set: { id: 'sm7', name: 'Celestial Storm', cardCount: { total: 183, official: 168 } },
    rarity: 'Common',
    stage: 'Basic',
    variants: { firstEdition: false, holo: false, normal: true, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'normal' }],
  },
  'hgss4-1': {
    id: 'hgss4-1',
    localId: '1',
    name: 'Aggron',
    image: 'https://assets.tcgdex.net/en/hgss/hgss4/1',
    category: 'Pokemon',
    set: { id: 'hgss4', name: 'Triumphant', cardCount: { total: 103, official: 102 } },
    rarity: 'Holo Rare',
    stage: 'Stage2',
    variants: { firstEdition: false, holo: true, normal: false, reverse: true, wPromo: false },
    variants_detailed: [{ type: 'holo' }, { type: 'reverse' }],
  },
  'sv03.5-026': {
    id: 'sv03.5-026',
    localId: '026',
    name: 'Raichu',
    image: 'https://assets.tcgdex.net/en/sv/sv03.5/026',
    category: 'Pokemon',
    set: { id: 'sv03.5', name: '151', cardCount: { total: 207, official: 165 } },
    rarity: 'Rare',
    stage: 'Stage1',
    variants: { firstEdition: false, holo: true, normal: false, reverse: true, wPromo: false },
    variants_detailed: [{ type: 'holo' }, { type: 'reverse' }, { type: 'holo', foil: 'cosmos' }],
  },
  'A1-003': {
    id: 'A1-003',
    localId: '003',
    name: 'Venusaur',
    image: 'https://assets.tcgdex.net/en/tcgp/A1/003',
    category: 'Pokemon',
    set: { id: 'A1', name: 'Genetic Apex', cardCount: { total: 286, official: 226 } },
    rarity: 'Three Diamond',
    stage: 'Stage2',
    variants: { firstEdition: false, holo: false, normal: true, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'normal' }],
  },
  'sv10.5b-171': {
    id: 'sv10.5b-171',
    localId: '171',
    name: 'Victini',
    image: 'https://assets.tcgdex.net/en/sv/sv10.5b/171',
    category: 'Pokemon',
    set: { id: 'sv10.5b', name: 'Black Bolt', cardCount: { total: 172, official: 86 } },
    rarity: 'Black White Rare',
    stage: 'Basic',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'sv10.5w-173': {
    id: 'sv10.5w-173',
    localId: '173',
    name: 'Reshiram ex',
    image: 'https://assets.tcgdex.net/en/sv/sv10.5w/173',
    category: 'Pokemon',
    set: { id: 'sv10.5w', name: 'White Flare', cardCount: { total: 173, official: 86 } },
    rarity: 'Black White Rare',
    stage: 'Basic',
    suffix: 'ex',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'sv10.5b-172': {
    id: 'sv10.5b-172',
    localId: '172',
    name: 'Zekrom ex',
    image: 'https://assets.tcgdex.net/en/sv/sv10.5b/172',
    category: 'Pokemon',
    set: { id: 'sv10.5b', name: 'Black Bolt', cardCount: { total: 172, official: 86 } },
    rarity: 'Black White Rare',
    stage: 'Basic',
    suffix: 'ex',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'swsh4-9': {
    id: 'swsh4-9',
    localId: '9',
    name: 'Celebi',
    image: 'https://assets.tcgdex.net/en/swsh/swsh4/9',
    category: 'Pokemon',
    set: { id: 'swsh4', name: 'Vivid Voltage', cardCount: { total: 203, official: 185 } },
    rarity: 'Amazing Rare',
    stage: 'Basic',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'swsh4.5-17': {
    id: 'swsh4.5-17',
    localId: '17',
    name: 'Reshiram',
    image: 'https://assets.tcgdex.net/en/swsh/swsh4.5/17',
    category: 'Pokemon',
    set: { id: 'swsh4.5', name: 'Shining Fates', cardCount: { total: 73, official: 72 } },
    rarity: 'Amazing Rare',
    stage: 'Basic',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'swsh4.5-21': {
    id: 'swsh4.5-21',
    localId: '21',
    name: 'Kyogre',
    image: 'https://assets.tcgdex.net/en/swsh/swsh4.5/21',
    category: 'Pokemon',
    set: { id: 'swsh4.5', name: 'Shining Fates', cardCount: { total: 73, official: 72 } },
    rarity: 'Amazing Rare',
    stage: 'Basic',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'swsh10.5-004': {
    id: 'swsh10.5-004',
    localId: '004',
    name: 'Radiant Venusaur',
    image: 'https://assets.tcgdex.net/en/swsh/swsh10.5/004',
    category: 'Pokemon',
    set: { id: 'swsh10.5', name: 'Pokémon GO', cardCount: { total: 88, official: 78 } },
    rarity: 'Radiant Rare',
    stage: 'Basic',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'swsh12-016': {
    id: 'swsh12-016',
    localId: '016',
    name: 'Radiant Tsareena',
    image: 'https://assets.tcgdex.net/en/swsh/swsh12/016',
    category: 'Pokemon',
    set: { id: 'swsh12', name: 'Silver Tempest', cardCount: { total: 215, official: 195 } },
    rarity: 'Radiant Rare',
    stage: 'Basic',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'swsh12.5-020': {
    id: 'swsh12.5-020',
    localId: '020',
    name: 'Radiant Charizard',
    image: 'https://assets.tcgdex.net/en/swsh/swsh12.5/020',
    category: 'Pokemon',
    set: { id: 'swsh12.5', name: 'Crown Zenith', cardCount: { total: 160, official: 159 } },
    rarity: 'Radiant Rare',
    stage: 'Basic',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'sv06.5-058': {
    id: 'sv06.5-058',
    localId: '058',
    name: 'Dangerous Laser',
    image: 'https://assets.tcgdex.net/en/sv/sv06.5/058',
    category: 'Trainer',
    trainerType: 'Item',
    set: { id: 'sv06.5', name: 'Shrouded Fable', cardCount: { total: 99, official: 64 } },
    rarity: 'ACE SPEC Rare',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'sv08.5-116': {
    id: 'sv08.5-116',
    localId: '116',
    name: 'Max Rod',
    image: 'https://assets.tcgdex.net/en/sv/sv08.5/116',
    category: 'Trainer',
    trainerType: 'Item',
    set: { id: 'sv08.5', name: 'Prismatic Evolutions', cardCount: { total: 180, official: 131 } },
    rarity: 'ACE SPEC Rare',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'sv07-134': {
    id: 'sv07-134',
    localId: '134',
    name: 'Deluxe Bomb',
    image: 'https://assets.tcgdex.net/en/sv/sv07/134',
    category: 'Trainer',
    trainerType: 'Tool',
    set: { id: 'sv07', name: 'Stellar Crown', cardCount: { total: 175, official: 142 } },
    rarity: 'ACE SPEC Rare',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  '30th-157': {
    id: '30th-157',
    localId: '157',
    name: 'Mewtwo ex',
    image: 'https://assets.tcgdex.net/en/me/30th/157',
    category: 'Pokemon',
    set: { id: '30th', name: '30th Celebration', cardCount: { total: 158, official: 128 } },
    rarity: 'Futuristic Rare',
    stage: 'Basic',
    suffix: 'EX',
    variants: { firstEdition: false, holo: false, normal: true, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'normal' }],
  },
  'A1a-085': {
    id: 'A1a-085',
    localId: '085',
    name: 'Celebi ex',
    image: 'https://assets.tcgdex.net/en/tcgp/A1a/085',
    category: 'Pokemon',
    set: { id: 'A1a', name: 'Mythical Island', cardCount: { total: 86, official: 68 } },
    rarity: 'Three Star',
    stage: 'Basic',
    suffix: 'EX',
    variants: { firstEdition: false, holo: false, normal: true, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'normal' }],
  },
  'B1a-087': {
    id: 'B1a-087',
    localId: '087',
    name: 'Mega Charizard Y ex',
    image: 'https://assets.tcgdex.net/en/tcgp/B1a/087',
    category: 'Pokemon',
    set: { id: 'B1a', name: 'Crimson Blaze', cardCount: { total: 103, official: 69 } },
    rarity: 'Three Star',
    stage: 'Stage2',
    suffix: 'EX',
    variants: { firstEdition: false, holo: false, normal: true, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'normal' }],
  },
  'sm115-69': {
    id: 'sm115-69',
    localId: '69',
    name: 'Moltres & Zapdos & Articuno GX',
    image: 'https://assets.tcgdex.net/en/sm/sm115/69',
    category: 'Pokemon',
    set: { id: 'sm115', name: 'Hidden Fates', cardCount: { total: 69, official: 68 } },
    rarity: 'Secret Rare',
    suffix: 'TAG TEAM-GX',
    variants: { firstEdition: false, holo: false, normal: true, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'normal' }],
  },
  'swsh4.5-73': {
    id: 'swsh4.5-73',
    localId: '73',
    name: 'Alcremie VMAX',
    image: 'https://assets.tcgdex.net/en/swsh/swsh4.5/73',
    category: 'Pokemon',
    set: { id: 'swsh4.5', name: 'Shining Fates', cardCount: { total: 73, official: 72 } },
    rarity: 'Secret Rare',
    stage: 'VMAX',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo', foil: 'rainbow' }],
  },
  'swsh3.5-74': {
    id: 'swsh3.5-74',
    localId: '74',
    name: 'Charizard VMAX',
    image: 'https://assets.tcgdex.net/en/swsh/swsh3.5/74',
    category: 'Pokemon',
    set: { id: 'swsh3.5', name: "Champion's Path", cardCount: { total: 80, official: 73 } },
    rarity: 'Secret Rare',
    stage: 'VMAX',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'sv04.5-092': {
    id: 'sv04.5-092',
    localId: '092',
    name: 'Oddish',
    image: 'https://assets.tcgdex.net/en/sv/sv04.5/092',
    category: 'Pokemon',
    set: { id: 'sv04.5', name: 'Paldean Fates', cardCount: { total: 245, official: 91 } },
    rarity: 'Shiny rare',
    stage: 'Basic',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'sma-SV71': {
    id: 'sma-SV71',
    localId: 'SV71',
    name: 'Guzzlord-GX',
    image: 'https://assets.tcgdex.net/en/sm/sma/SV71',
    category: 'Pokemon',
    set: { id: 'sma', name: 'Hidden Fates Shiny Vault', cardCount: { total: 94, official: 94 } },
    rarity: 'Shiny rare',
    suffix: 'GX',
    variants: { firstEdition: false, holo: false, normal: true, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'normal' }],
  },
  'B1a-089': {
    id: 'B1a-089',
    localId: '089',
    name: 'Gloom',
    image: 'https://assets.tcgdex.net/en/tcgp/B1a/089',
    category: 'Pokemon',
    set: { id: 'B1a', name: 'Crimson Blaze', cardCount: { total: 103, official: 69 } },
    rarity: 'One Shiny',
    stage: 'Stage1',
    variants: { firstEdition: false, holo: false, normal: true, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'normal' }],
  },
  'swsh4.5sv-SV105': {
    id: 'swsh4.5sv-SV105',
    localId: 'SV105',
    name: 'Rillaboom V',
    category: 'Pokemon',
    set: {
      id: 'swsh4.5sv',
      name: 'Shining Fates Shiny Vault',
      cardCount: { total: 122, official: 122 },
    },
    rarity: 'Shiny rare V',
    stage: 'Basic',
    suffix: 'V',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'sv04.5-212': {
    id: 'sv04.5-212',
    localId: '212',
    name: 'Forretress ex',
    image: 'https://assets.tcgdex.net/en/sv/sv04.5/212',
    category: 'Pokemon',
    set: { id: 'sv04.5', name: 'Paldean Fates', cardCount: { total: 245, official: 91 } },
    rarity: 'Shiny Ultra Rare',
    stage: 'Stage1',
    suffix: 'ex',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'B1a-098': {
    id: 'B1a-098',
    localId: '098',
    name: 'Buzzwole ex',
    image: 'https://assets.tcgdex.net/en/tcgp/B1a/098',
    category: 'Pokemon',
    set: { id: 'B1a', name: 'Crimson Blaze', cardCount: { total: 103, official: 69 } },
    rarity: 'Two Shiny',
    stage: 'Basic',
    suffix: 'EX',
    variants: { firstEdition: false, holo: false, normal: true, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'normal' }],
  },
  'swsh4.5sv-SV106': {
    id: 'swsh4.5sv-SV106',
    localId: 'SV106',
    name: 'Rillaboom VMAX',
    category: 'Pokemon',
    set: {
      id: 'swsh4.5sv',
      name: 'Shining Fates Shiny Vault',
      cardCount: { total: 122, official: 122 },
    },
    rarity: 'Shiny rare VMAX',
    stage: 'VMAX',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'swsh4.5sv-SV107': {
    id: 'swsh4.5sv-SV107',
    localId: 'SV107',
    name: 'Charizard VMAX',
    category: 'Pokemon',
    set: {
      id: 'swsh4.5sv',
      name: 'Shining Fates Shiny Vault',
      cardCount: { total: 122, official: 122 },
    },
    rarity: 'Shiny rare VMAX',
    stage: 'VMAX',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'swsh4.5sv-SV109': {
    id: 'swsh4.5sv-SV109',
    localId: 'SV109',
    name: 'Centiskorch VMAX',
    category: 'Pokemon',
    set: {
      id: 'swsh4.5sv',
      name: 'Shining Fates Shiny Vault',
      cardCount: { total: 122, official: 122 },
    },
    rarity: 'Shiny rare VMAX',
    stage: 'VMAX',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'xyp-XY84': {
    id: 'xyp-XY84',
    localId: 'XY84',
    name: 'Pikachu EX',
    image: 'https://assets.tcgdex.net/en/xy/xyp/XY84',
    category: 'Pokemon',
    set: { id: 'xyp', name: 'XY Black Star Promos', cardCount: { total: 216, official: 211 } },
    rarity: 'Promo',
    suffix: 'EX',
    variants: { firstEdition: false, holo: false, normal: true, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'normal' }],
  },
  'swsh3.5-1': {
    id: 'swsh3.5-1',
    localId: '1',
    name: 'Venusaur V',
    image: 'https://assets.tcgdex.net/en/swsh/swsh3.5/1',
    category: 'Pokemon',
    set: { id: 'swsh3.5', name: "Champion's Path", cardCount: { total: 80, official: 73 } },
    rarity: 'Holo Rare V',
    stage: 'Basic',
    suffix: 'V',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'swsh1-1': {
    id: 'swsh1-1',
    localId: '1',
    name: 'Celebi V',
    image: 'https://assets.tcgdex.net/en/swsh/swsh1/1',
    category: 'Pokemon',
    set: { id: 'swsh1', name: 'Sword & Shield', cardCount: { total: 216, official: 202 } },
    rarity: 'Holo Rare V',
    stage: 'Basic',
    suffix: 'V',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'sm9-1': {
    id: 'sm9-1',
    localId: '1',
    name: 'Celebi & Venusaur GX',
    image: 'https://assets.tcgdex.net/en/sm/sm9/1',
    category: 'Pokemon',
    set: { id: 'sm9', name: 'Team Up', cardCount: { total: 196, official: 181 } },
    rarity: 'Ultra Rare',
    suffix: 'TAG TEAM-GX',
    variants: { firstEdition: false, holo: false, normal: true, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'normal' }],
  },
  'sm10-1': {
    id: 'sm10-1',
    localId: '1',
    name: 'Pheromosa & Buzzwole GX',
    image: 'https://assets.tcgdex.net/en/sm/sm10/1',
    category: 'Pokemon',
    set: { id: 'sm10', name: 'Unbroken Bonds', cardCount: { total: 234, official: 214 } },
    rarity: 'Ultra Rare',
    suffix: 'TAG TEAM-GX',
    variants: { firstEdition: false, holo: false, normal: true, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'normal' }],
  },
  'sm12-1': {
    id: 'sm12-1',
    localId: '1',
    name: 'Venusaur & Snivy GX',
    image: 'https://assets.tcgdex.net/en/sm/sm12/1',
    category: 'Pokemon',
    set: { id: 'sm12', name: 'Cosmic Eclipse', cardCount: { total: 271, official: 236 } },
    rarity: 'Ultra Rare',
    suffix: 'TAG TEAM-GX',
    variants: { firstEdition: false, holo: false, normal: true, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'normal' }],
  },
  'swsh3-2': {
    id: 'swsh3-2',
    localId: '2',
    name: 'Butterfree VMAX',
    image: 'https://assets.tcgdex.net/en/swsh/swsh3/2',
    category: 'Pokemon',
    set: { id: 'swsh3', name: 'Darkness Ablaze', cardCount: { total: 201, official: 189 } },
    rarity: 'Holo Rare VMAX',
    stage: 'VMAX',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'cel25-7': {
    id: 'cel25-7',
    localId: '7',
    name: 'Flying Pikachu VMAX',
    image: 'https://assets.tcgdex.net/en/swsh/cel25/7',
    category: 'Pokemon',
    set: { id: 'cel25', name: 'Celebrations', cardCount: { total: 25, official: 25 } },
    rarity: 'Holo Rare VMAX',
    stage: 'VMAX',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'swsh6-8': {
    id: 'swsh6-8',
    localId: '8',
    name: 'Celebi VMAX',
    image: 'https://assets.tcgdex.net/en/swsh/swsh6/8',
    category: 'Pokemon',
    set: { id: 'swsh6', name: 'Chilling Reign', cardCount: { total: 233, official: 198 } },
    rarity: 'Holo Rare VMAX',
    stage: 'VMAX',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'swsh12-008': {
    id: 'swsh12-008',
    localId: '008',
    name: 'Serperior VSTAR',
    image: 'https://assets.tcgdex.net/en/swsh/swsh12/008',
    category: 'Pokemon',
    set: { id: 'swsh12', name: 'Silver Tempest', cardCount: { total: 215, official: 195 } },
    rarity: 'Holo Rare VSTAR',
    stage: 'VSTAR',
    suffix: 'V',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'swsh12.5-014': {
    id: 'swsh12.5-014',
    localId: '014',
    name: 'Leafeon VSTAR',
    image: 'https://assets.tcgdex.net/en/swsh/swsh12.5/014',
    category: 'Pokemon',
    set: { id: 'swsh12.5', name: 'Crown Zenith', cardCount: { total: 160, official: 159 } },
    rarity: 'Holo Rare VSTAR',
    stage: 'VSTAR',
    suffix: 'V',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'swsh9-014': {
    id: 'swsh9-014',
    localId: '014',
    name: 'Shaymin VSTAR',
    image: 'https://assets.tcgdex.net/en/swsh/swsh9/014',
    category: 'Pokemon',
    set: { id: 'swsh9', name: 'Brilliant Stars', cardCount: { total: 186, official: 172 } },
    rarity: 'Holo Rare VSTAR',
    stage: 'VSTAR',
    suffix: 'V',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }, { type: 'holo' }],
  },
  'swsh10tg-TG01': {
    id: 'swsh10tg-TG01',
    localId: 'TG01',
    name: 'Abomasnow',
    category: 'Pokemon',
    set: {
      id: 'swsh10tg',
      name: 'Astral Radiance Trainer Gallery',
      cardCount: { total: 30, official: 30 },
    },
    rarity: 'Rare',
    stage: 'Stage1',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'swsh11tg-TG03': {
    id: 'swsh11tg-TG03',
    localId: 'TG03',
    name: 'Charizard',
    category: 'Pokemon',
    set: {
      id: 'swsh11tg',
      name: 'Lost Origin Trainer Gallery',
      cardCount: { total: 30, official: 30 },
    },
    rarity: 'Rare',
    stage: 'Stage2',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'swsh12tg-TG05': {
    id: 'swsh12tg-TG05',
    localId: 'TG05',
    name: 'Gardevoir',
    category: 'Pokemon',
    set: {
      id: 'swsh12tg',
      name: 'Silver Tempest Trainer Gallery',
      cardCount: { total: 30, official: 30 },
    },
    rarity: 'Holo Rare',
    stage: 'Stage2',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  '30th-023': {
    id: '30th-023',
    localId: '023',
    name: 'Pikachu',
    image: 'https://assets.tcgdex.net/en/me/30th/023',
    category: 'Pokemon',
    set: { id: '30th', name: '30th Celebration', cardCount: { total: 158, official: 128 } },
    rarity: 'Pikachu Rare',
    stage: 'Basic',
    variants: { firstEdition: false, holo: false, normal: true, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'normal' }],
  },
  '30th-024': {
    id: '30th-024',
    localId: '024',
    name: 'Pikachu',
    image: 'https://assets.tcgdex.net/en/me/30th/024',
    category: 'Pokemon',
    set: { id: '30th', name: '30th Celebration', cardCount: { total: 158, official: 128 } },
    rarity: 'Pikachu Rare',
    stage: 'Basic',
    variants: { firstEdition: false, holo: false, normal: true, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'normal' }],
  },
  '30th-025': {
    id: '30th-025',
    localId: '025',
    name: 'Pikachu',
    image: 'https://assets.tcgdex.net/en/me/30th/025',
    category: 'Pokemon',
    set: { id: '30th', name: '30th Celebration', cardCount: { total: 158, official: 128 } },
    rarity: 'Pikachu Rare',
    stage: 'Basic',
    variants: { firstEdition: false, holo: false, normal: true, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'normal' }],
  },
  'swsh3-3': {
    id: 'swsh3-3',
    localId: '3',
    name: 'Paras',
    image: 'https://assets.tcgdex.net/en/swsh/swsh3/3',
    category: 'Pokemon',
    set: { id: 'swsh3', name: 'Darkness Ablaze', cardCount: { total: 201, official: 189 } },
    rarity: 'Common',
    stage: 'Basic',
    variants: { firstEdition: false, holo: false, normal: true, reverse: true, wPromo: false },
    variants_detailed: [{ type: 'normal' }, { type: 'reverse' }],
  },
  'swsh3-4': {
    id: 'swsh3-4',
    localId: '4',
    name: 'Parasect',
    image: 'https://assets.tcgdex.net/en/swsh/swsh3/4',
    category: 'Pokemon',
    set: { id: 'swsh3', name: 'Darkness Ablaze', cardCount: { total: 201, official: 189 } },
    rarity: 'Uncommon',
    stage: 'Stage1',
    variants: { firstEdition: false, holo: false, normal: true, reverse: true, wPromo: false },
    variants_detailed: [{ type: 'normal' }, { type: 'reverse' }],
  },
  'swsh3-5': {
    id: 'swsh3-5',
    localId: '5',
    name: 'Carnivine',
    image: 'https://assets.tcgdex.net/en/swsh/swsh3/5',
    category: 'Pokemon',
    set: { id: 'swsh3', name: 'Darkness Ablaze', cardCount: { total: 201, official: 189 } },
    rarity: 'Uncommon',
    stage: 'Basic',
    variants: { firstEdition: false, holo: false, normal: true, reverse: true, wPromo: false },
    variants_detailed: [{ type: 'normal' }, { type: 'reverse' }],
  },
  'swsh12tg-TG12': {
    id: 'swsh12tg-TG12',
    localId: 'TG12',
    name: 'Kricketune V',
    category: 'Pokemon',
    set: {
      id: 'swsh12tg',
      name: 'Silver Tempest Trainer Gallery',
      cardCount: { total: 30, official: 30 },
    },
    rarity: 'Holo Rare V',
    stage: 'Basic',
    suffix: 'V',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'swsh12tg-TG13': {
    id: 'swsh12tg-TG13',
    localId: 'TG13',
    name: 'Serperior V',
    category: 'Pokemon',
    set: {
      id: 'swsh12tg',
      name: 'Silver Tempest Trainer Gallery',
      cardCount: { total: 30, official: 30 },
    },
    rarity: 'Holo Rare V',
    stage: 'Basic',
    suffix: 'V',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'swsh12tg-TG14': {
    id: 'swsh12tg-TG14',
    localId: 'TG14',
    name: 'Blaziken V',
    category: 'Pokemon',
    set: {
      id: 'swsh12tg',
      name: 'Silver Tempest Trainer Gallery',
      cardCount: { total: 30, official: 30 },
    },
    rarity: 'Holo Rare V',
    stage: 'Basic',
    suffix: 'V',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'swsh12tg-TG15': {
    id: 'swsh12tg-TG15',
    localId: 'TG15',
    name: 'Blaziken VMAX',
    category: 'Pokemon',
    set: {
      id: 'swsh12tg',
      name: 'Silver Tempest Trainer Gallery',
      cardCount: { total: 30, official: 30 },
    },
    rarity: 'Holo Rare VMAX',
    stage: 'VMAX',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'swsh12tg-TG19': {
    id: 'swsh12tg-TG19',
    localId: 'TG19',
    name: 'Corviknight VMAX',
    category: 'Pokemon',
    set: {
      id: 'swsh12tg',
      name: 'Silver Tempest Trainer Gallery',
      cardCount: { total: 30, official: 30 },
    },
    rarity: 'Holo Rare VMAX',
    stage: 'VMAX',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'swsh12tg-TG20': {
    id: 'swsh12tg-TG20',
    localId: 'TG20',
    name: 'Rayquaza VMAX',
    category: 'Pokemon',
    set: {
      id: 'swsh12tg',
      name: 'Silver Tempest Trainer Gallery',
      cardCount: { total: 30, official: 30 },
    },
    rarity: 'Holo Rare VMAX',
    stage: 'VMAX',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'swsh9tg-TG29': {
    id: 'swsh9tg-TG29',
    localId: 'TG29',
    name: 'Single Strike Urshifu VMAX',
    category: 'Pokemon',
    set: {
      id: 'swsh9tg',
      name: 'Brilliant Stars Trainer Gallery',
      cardCount: { total: 30, official: 30 },
    },
    rarity: 'Secret Rare',
    stage: 'VMAX',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'swsh10tg-TG29': {
    id: 'swsh10tg-TG29',
    localId: 'TG29',
    name: 'Ice Rider Calyrex VMAX',
    category: 'Pokemon',
    set: {
      id: 'swsh10tg',
      name: 'Astral Radiance Trainer Gallery',
      cardCount: { total: 30, official: 30 },
    },
    rarity: 'Secret Rare',
    stage: 'VMAX',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }, { type: 'holo', foil: 'gold' }],
  },
  'swsh12tg-TG29': {
    id: 'swsh12tg-TG29',
    localId: 'TG29',
    name: 'Rayquaza VMAX',
    category: 'Pokemon',
    set: {
      id: 'swsh12tg',
      name: 'Silver Tempest Trainer Gallery',
      cardCount: { total: 30, official: 30 },
    },
    rarity: 'Secret Rare',
    stage: 'VMAX',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo', foil: 'gold' }],
  },
  'swsh12tg-TG23': {
    id: 'swsh12tg-TG23',
    localId: 'TG23',
    name: 'Friends in Galar',
    category: 'Trainer',
    trainerType: 'Supporter',
    set: {
      id: 'swsh12tg',
      name: 'Silver Tempest Trainer Gallery',
      cardCount: { total: 30, official: 30 },
    },
    rarity: 'Full Art Trainer',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'swsh12tg-TG24': {
    id: 'swsh12tg-TG24',
    localId: 'TG24',
    name: 'Gordie',
    category: 'Trainer',
    trainerType: 'Supporter',
    set: {
      id: 'swsh12tg',
      name: 'Silver Tempest Trainer Gallery',
      cardCount: { total: 30, official: 30 },
    },
    rarity: 'Full Art Trainer',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'swsh12tg-TG25': {
    id: 'swsh12tg-TG25',
    localId: 'TG25',
    name: 'Judge',
    category: 'Trainer',
    trainerType: 'Supporter',
    set: {
      id: 'swsh12tg',
      name: 'Silver Tempest Trainer Gallery',
      cardCount: { total: 30, official: 30 },
    },
    rarity: 'Full Art Trainer',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'sv03.5-003': {
    id: 'sv03.5-003',
    localId: '003',
    name: 'Venusaur ex',
    image: 'https://assets.tcgdex.net/en/sv/sv03.5/003',
    category: 'Pokemon',
    set: { id: 'sv03.5', name: '151', cardCount: { total: 207, official: 165 } },
    rarity: 'Double rare',
    stage: 'Stage2',
    suffix: 'ex',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'sv03.5-006': {
    id: 'sv03.5-006',
    localId: '006',
    name: 'Charizard ex',
    image: 'https://assets.tcgdex.net/en/sv/sv03.5/006',
    category: 'Pokemon',
    set: { id: 'sv03.5', name: '151', cardCount: { total: 207, official: 165 } },
    rarity: 'Double rare',
    stage: 'Stage2',
    suffix: 'ex',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'sv03.5-009': {
    id: 'sv03.5-009',
    localId: '009',
    name: 'Blastoise ex',
    image: 'https://assets.tcgdex.net/en/sv/sv03.5/009',
    category: 'Pokemon',
    set: { id: 'sv03.5', name: '151', cardCount: { total: 207, official: 165 } },
    rarity: 'Double rare',
    stage: 'Stage2',
    suffix: 'ex',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }, { type: 'holo' }],
  },
  'sv03.5-182': {
    id: 'sv03.5-182',
    localId: '182',
    name: 'Venusaur ex',
    image: 'https://assets.tcgdex.net/en/sv/sv03.5/182',
    category: 'Pokemon',
    set: { id: 'sv03.5', name: '151', cardCount: { total: 207, official: 165 } },
    rarity: 'Ultra Rare',
    stage: 'Stage2',
    suffix: 'ex',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'sv03.5-183': {
    id: 'sv03.5-183',
    localId: '183',
    name: 'Charizard ex',
    image: 'https://assets.tcgdex.net/en/sv/sv03.5/183',
    category: 'Pokemon',
    set: { id: 'sv03.5', name: '151', cardCount: { total: 207, official: 165 } },
    rarity: 'Ultra Rare',
    stage: 'Stage2',
    suffix: 'ex',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'sv03.5-184': {
    id: 'sv03.5-184',
    localId: '184',
    name: 'Blastoise ex',
    image: 'https://assets.tcgdex.net/en/sv/sv03.5/184',
    category: 'Pokemon',
    set: { id: 'sv03.5', name: '151', cardCount: { total: 207, official: 165 } },
    rarity: 'Ultra Rare',
    stage: 'Stage2',
    suffix: 'ex',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'sv03.5-166': {
    id: 'sv03.5-166',
    localId: '166',
    name: 'Bulbasaur',
    image: 'https://assets.tcgdex.net/en/sv/sv03.5/166',
    category: 'Pokemon',
    set: { id: 'sv03.5', name: '151', cardCount: { total: 207, official: 165 } },
    rarity: 'Illustration rare',
    stage: 'Basic',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'sv03.5-168': {
    id: 'sv03.5-168',
    localId: '168',
    name: 'Charmander',
    image: 'https://assets.tcgdex.net/en/sv/sv03.5/168',
    category: 'Pokemon',
    set: { id: 'sv03.5', name: '151', cardCount: { total: 207, official: 165 } },
    rarity: 'Illustration rare',
    stage: 'Basic',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'sv03.5-170': {
    id: 'sv03.5-170',
    localId: '170',
    name: 'Squirtle',
    image: 'https://assets.tcgdex.net/en/sv/sv03.5/170',
    category: 'Pokemon',
    set: { id: 'sv03.5', name: '151', cardCount: { total: 207, official: 165 } },
    rarity: 'Illustration rare',
    stage: 'Basic',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'sv03.5-198': {
    id: 'sv03.5-198',
    localId: '198',
    name: 'Venusaur ex',
    image: 'https://assets.tcgdex.net/en/sv/sv03.5/198',
    category: 'Pokemon',
    set: { id: 'sv03.5', name: '151', cardCount: { total: 207, official: 165 } },
    rarity: 'Special illustration rare',
    stage: 'Stage2',
    suffix: 'ex',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'sv03.5-199': {
    id: 'sv03.5-199',
    localId: '199',
    name: 'Charizard ex',
    image: 'https://assets.tcgdex.net/en/sv/sv03.5/199',
    category: 'Pokemon',
    set: { id: 'sv03.5', name: '151', cardCount: { total: 207, official: 165 } },
    rarity: 'Special illustration rare',
    stage: 'Stage2',
    suffix: 'ex',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'sv03.5-200': {
    id: 'sv03.5-200',
    localId: '200',
    name: 'Blastoise ex',
    image: 'https://assets.tcgdex.net/en/sv/sv03.5/200',
    category: 'Pokemon',
    set: { id: 'sv03.5', name: '151', cardCount: { total: 207, official: 165 } },
    rarity: 'Special illustration rare',
    stage: 'Stage2',
    suffix: 'ex',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'sv03.5-205': {
    id: 'sv03.5-205',
    localId: '205',
    name: 'Mew ex',
    image: 'https://assets.tcgdex.net/en/sv/sv03.5/205',
    category: 'Pokemon',
    set: { id: 'sv03.5', name: '151', cardCount: { total: 207, official: 165 } },
    rarity: 'Hyper rare',
    stage: 'Basic',
    suffix: 'ex',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [
      { type: 'holo' },
      { type: 'holo', foil: 'gold' },
      { type: 'holo', foil: 'gold' },
      { type: 'metal', foil: 'gold' },
    ],
  },
  'sv03.5-206': {
    id: 'sv03.5-206',
    localId: '206',
    name: 'Switch',
    image: 'https://assets.tcgdex.net/en/sv/sv03.5/206',
    category: 'Trainer',
    trainerType: 'Item',
    set: { id: 'sv03.5', name: '151', cardCount: { total: 207, official: 165 } },
    rarity: 'Hyper rare',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }, { type: 'holo', foil: 'gold' }],
  },
  'sv03.5-207': {
    id: 'sv03.5-207',
    localId: '207',
    name: 'Basic Psychic Energy',
    image: 'https://assets.tcgdex.net/en/sv/sv03.5/207',
    category: 'Energy',
    set: { id: 'sv03.5', name: '151', cardCount: { total: 207, official: 165 } },
    rarity: 'Hyper rare',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }, { type: 'holo', foil: 'gold' }],
  },
  'sv03.5-002': {
    id: 'sv03.5-002',
    localId: '002',
    name: 'Ivysaur',
    image: 'https://assets.tcgdex.net/en/sv/sv03.5/002',
    category: 'Pokemon',
    set: { id: 'sv03.5', name: '151', cardCount: { total: 207, official: 165 } },
    rarity: 'Uncommon',
    stage: 'Stage1',
    variants: { firstEdition: false, holo: false, normal: true, reverse: true, wPromo: false },
    variants_detailed: [{ type: 'normal' }, { type: 'reverse' }],
  },
  'sv03.5-005': {
    id: 'sv03.5-005',
    localId: '005',
    name: 'Charmeleon',
    image: 'https://assets.tcgdex.net/en/sv/sv03.5/005',
    category: 'Pokemon',
    set: { id: 'sv03.5', name: '151', cardCount: { total: 207, official: 165 } },
    rarity: 'Uncommon',
    stage: 'Stage1',
    variants: { firstEdition: false, holo: true, normal: true, reverse: true, wPromo: false },
    variants_detailed: [{ type: 'normal' }, { type: 'reverse' }, { type: 'holo', foil: 'cosmos' }],
  },
  'sv08.5-074': {
    id: 'sv08.5-074',
    localId: '074',
    name: 'Eevee',
    image: 'https://assets.tcgdex.net/en/sv/sv08.5/074',
    category: 'Pokemon',
    set: { id: 'sv08.5', name: 'Prismatic Evolutions', cardCount: { total: 180, official: 131 } },
    rarity: 'Common',
    stage: 'Basic',
    variants: { firstEdition: false, holo: false, normal: true, reverse: true, wPromo: false },
    variants_detailed: [
      { type: 'normal' },
      { type: 'reverse' },
      { type: 'reverse', foil: 'pokeball' },
      { type: 'reverse', foil: 'masterball' },
      { type: 'reverse', foil: 'cosmos' },
    ],
  },
  'sv03.5-001': {
    id: 'sv03.5-001',
    localId: '001',
    name: 'Bulbasaur',
    image: 'https://assets.tcgdex.net/en/sv/sv03.5/001',
    category: 'Pokemon',
    set: { id: 'sv03.5', name: '151', cardCount: { total: 207, official: 165 } },
    rarity: 'Common',
    stage: 'Basic',
    variants: { firstEdition: false, holo: false, normal: true, reverse: true, wPromo: false },
    variants_detailed: [
      { type: 'normal' },
      { type: 'reverse' },
      { type: 'normal' },
      { type: 'reverse', foil: 'cosmos' },
    ],
  },
  'sv03.5-004': {
    id: 'sv03.5-004',
    localId: '004',
    name: 'Charmander',
    image: 'https://assets.tcgdex.net/en/sv/sv03.5/004',
    category: 'Pokemon',
    set: { id: 'sv03.5', name: '151', cardCount: { total: 207, official: 165 } },
    rarity: 'Common',
    stage: 'Basic',
    variants: { firstEdition: false, holo: true, normal: true, reverse: true, wPromo: false },
    variants_detailed: [
      { type: 'normal' },
      { type: 'reverse' },
      { type: 'normal' },
      { type: 'holo', foil: 'cosmos' },
      { type: 'reverse' },
      { type: 'reverse', foil: 'cosmos' },
    ],
  },
  'sv08.5-001': {
    id: 'sv08.5-001',
    localId: '001',
    name: 'Exeggcute',
    image: 'https://assets.tcgdex.net/en/sv/sv08.5/001',
    category: 'Pokemon',
    set: { id: 'sv08.5', name: 'Prismatic Evolutions', cardCount: { total: 180, official: 131 } },
    rarity: 'Common',
    stage: 'Basic',
    variants: { firstEdition: false, holo: false, normal: true, reverse: true, wPromo: false },
    variants_detailed: [
      { type: 'normal' },
      { type: 'reverse' },
      { type: 'reverse', foil: 'pokeball' },
      { type: 'reverse', foil: 'masterball' },
    ],
  },
  'dp7-96': {
    id: 'dp7-96',
    localId: '96',
    name: 'Dusknoir',
    image: 'https://assets.tcgdex.net/en/dp/dp7/96',
    category: 'Pokemon',
    set: { id: 'dp7', name: 'Stormfront', cardCount: { total: 106, official: 100 } },
    rarity: 'Rare Holo LV.X',
    stage: 'LEVEL-UP',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'hgss3-83': {
    id: 'hgss3-83',
    localId: '83',
    name: 'Raichu',
    image: 'https://assets.tcgdex.net/en/hgss/hgss3/83',
    category: 'Pokemon',
    set: { id: 'hgss3', name: 'Undaunted', cardCount: { total: 91, official: 90 } },
    rarity: 'Rare PRIME',
    stage: 'Stage1',
    suffix: 'Prime',
    variants: { firstEdition: false, holo: true, normal: false, reverse: false, wPromo: false },
    variants_detailed: [{ type: 'holo' }],
  },
  'me01-034': {
    id: 'me01-034',
    localId: '034',
    name: 'Kyogre',
    image: 'https://assets.tcgdex.net/en/me/me01/034',
    category: 'Pokemon',
    set: { id: 'me01', name: 'Mega Evolution', cardCount: { total: 188, official: 132 } },
    rarity: 'Rare',
    stage: 'Basic',
    variants: { firstEdition: false, holo: true, normal: false, reverse: true, wPromo: false },
    variants_detailed: [{ type: 'holo' }, { type: 'reverse' }, { type: 'holo', foil: 'cosmos' }],
  },
};
