/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ProjectsProjectIdSplatRouteImport } from './routes/projects/$projectId_.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdSplatRoute = ProjectsProjectIdSplatRouteImport.update({
  id: '/projects/$projectId_/$',
  path: '/projects/$projectId/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/blog/': typeof BlogIndexRoute
  '/projects/$projectId/$': typeof ProjectsProjectIdSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/blog': typeof BlogIndexRoute
  '/projects/$projectId/$': typeof ProjectsProjectIdSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/blog/': typeof BlogIndexRoute
  '/projects/$projectId_/$': typeof ProjectsProjectIdSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog/$slug'
    | '/projects/$projectId'
    | '/blog/'
    | '/projects/$projectId/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog/$slug'
    | '/projects/$projectId'
    | '/blog'
    | '/projects/$projectId/$'
  id:
    | '__root__'
    | '/'
    | '/blog/$slug'
    | '/projects/$projectId'
    | '/blog/'
    | '/projects/$projectId_/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ProjectsProjectIdSplatRoute: typeof ProjectsProjectIdSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId_/$': {
      id: '/projects/$projectId_/$'
      path: '/projects/$projectId/$'
      fullPath: '/projects/$projectId/$'
      preLoaderRoute: typeof ProjectsProjectIdSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogSlugRoute: BlogSlugRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  BlogIndexRoute: BlogIndexRoute,
  ProjectsProjectIdSplatRoute: ProjectsProjectIdSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
